### ISSUE TITLE
Bug lors de l'ajout d'une sous catégorie sur le Panel Admin Forum

### ISSUE THREAD

**Issue by deadfire24** [Aldric-L/DiamondCMS#1]
J'ai créé une catégorie globale du nom de "Recrutement"
J'ai ajouté une sous-catégorie du nom de "En attente"

Désormais mon panel admin de la page forum ressemble à ceci : https://prnt.sc/scj6dn

**Comment by Aldric-L** [comment]
Bonjour, 
Pouvez-vous me donner plus d'informations sur votre problème : puis-je avoir une capture d'écran de la console du navigateur ? (Clique droit->Inspecter->Console) Pouvez-vous aussi me donner la version du CMS ?

Pour votre problème, en ayant réalisé la même action que vous, je n'ai relevé qu'une petite erreur d'affichage (bien moins dérangeante que la votre) que j'ai corrigé. Pour en profiter, et voir si cela ne règle pas le problème, je vous invite à télécharger sur le github une version de développement de la mise à jour (les dossiers se trouvent dans le dossier docs->files). Choisissez le dossier qui se termine par 1-3 si vous êtes encore sur le Build C, ou 2-3 si vous êtes déjà sur le D. 

Tenez moi au courant. 
Bien à vous.

**Comment by Aldric-L** [comment]
Voici le lien du dossier, choisissez l'installateur en fonction des instructions : 

https://github.com/Aldric-L/DiamondCMS/tree/master/docs/files/
