### ISSUE TITLE
[BUG] you don't have permission

### ISSUE THREAD

**Issue by FireWax912** [Aldric-L/DiamondCMS#11]
Bonjour,

j'ai récemment voulu ajouter du contenu dans mon forum m'est impossible. Il me dit que je n'ai pas la permission alors que je suis diamond-master

cordialement,

**Comment by Aldric-L** [comment]
Bonjour, 
Même réponse que pour votre précédente question : il me faut plus d'informations ! Contexte de l'erreur, code erreur, page, etc...
Cordialement
AL

**Comment by FireWax912** [comment]
eh bien c'est la page du forum du CMS. Il s'agit d'une erreur 123 après cette raison dans le dev_error : 

Type: Alerte - 27/05/21 à 10:49:51 - Invalid argument supplied for foreach(). Affichée : Non - Levée dans /home/xyefzjky/public_html/views/themes/default/pages/forum/forum_scat.php à la ligne 16. 
Type: Alerte - 27/05/21 à 10:41:09 - Invalid argument supplied for foreach(). Affichée : Non - Levée dans /home/xyefzjky/public_html/views/themes/default/pages/forum/forum_scat.php à la ligne 16.

**Comment by Aldric-L** [comment]
Quel contenu avez-vous essayé d'ajouter ? Un sujet ? Un commentaire ? Une catégorie ?
Il semble bien que se soit une coquille dans le code. Je déploie un patch dans la journée si tel est le cas.

**Comment by FireWax912** [comment]
J'ai tout simplement essayé d'écrire un règlement pour mon serveur Garry's Mod du type :

-Freekill / Freeshoot / Freepunch interdit
- raison 2
- raison 3 
etc

merci de respecter
Cordialement,

Mais à chaque fois j'ai cette erreur

Merci de m'aider à régler ces problèmes =) .

Cordialement,

**Comment by Aldric-L** [comment]
Vous avez donc un problème à chaque fois que vous essayez de créer un sujet sur votre forum ?

**Comment by Aldric-L** [comment]
En consultant votre site, je constate effectivement un gros problème sur le forum : le compteur de message affiche un nombre négatif ce qui est absurde. Essayez de créer votre règlement dans une autre catégorie. Le problème vient peut être de là.

**Comment by FireWax912** [comment]
je viens de créer une nouvelle catégorie et sous catégorie et j'ai toujours cette erreur 403 forbidden

Cordialement

**Comment by Aldric-L** [comment]
Je vais étudier le problème en local. Je reviens vers vous dans la journée.
Cordialement.

**Comment by Aldric-L** [comment]
L'erreur de code que vous avez trouvé n'est pas un problème en réalité et ne cause pas votre disfonctionnement. Toutefois, elle sera corrigée dans un soucis de "propreté" du code. 

En local, je n'ai aucun problème ni sur PHP7 ni sur PHP8. C'est donc très étrange. Pouvez-vous m’autoriser à créer un compte sur votre site en me donnant la permission "Admin" (ou tout autre grade de rang 4, au minimum) afin que je puisse observer l'erreur par moi même ?

**Comment by FireWax912** [comment]
Oui bien sûr prévenez moi quand le compte est créé

Cordialement

**Comment by Aldric-L** [comment]
Bonjour,
Le compte "Support DiamondCMS" est créé. 
Merci encore pour votre investissement

**Comment by Aldric-L** [comment]
Je suis surpris, en utilisant le compte que vous m'avez octroyé je n'ai aucun problème pour utiliser le forum... Pouvez-vous me décrire exactement l'action qui pose problème ?

**Comment by FireWax912** [comment]
Eh bien c'est quand j'écris le règlement pour je ne sais quelle raison je ne peux pas. Cependant jai l'hypothèse qu'il s'agit du format avec lequel j'écris du genre :

Présentation

Règles 1 : blabla
Règles 2 : blabla

Etc

Cordialement

Je crois que ce format ne convient pas

Cordialement

**Comment by Aldric-L** [comment]
Pouvez vous essayer sans ce format ?

**Comment by Aldric-L** [comment]
Ps: En regardant les erreurs levées par votre configuration, je me permet de vous dire que vous n'avez pas correctement paramétré votre lien avec le serveur : vous devez retirer le ":27015" après l'adresse du serveur...

**Comment by FireWax912** [comment]
Eh bien j'ai déjà essayé de mettre juste une petite phrase comme

Voici le règlement du serveur

Et cela marche mais du coup il est impossible pour moi de faire mon
règlement

Cordialement

**Comment by FireWax912** [comment]
Je viens également de lire votre message pour le lien serveur-site le soucis est que j'ai déjà essayé toutes les formes c'est a dire en chiffres ou avec le lien actuel mais impossible de le relier pourtant je me suis renseigné auprès du support et le Query le Rcon sont correct

**Comment by FireWax912** [comment]
Du coup après ce petit problème PayPal et de forum serait vous disponible pour régler mon autre problème de liaison avec mon serveur gmod ?

**Comment by Aldric-L** [comment]
Bien sûr, j'y travaille déjà ;)

**Comment by Aldric-L** [comment]
Pour le forum, j'ai créé des sujets selon votre formatage et tout semble bien fonctionner... Je comprends pas bien

**Comment by Aldric-L** [comment]
Pour votre problème de liaison site-serveur, je vous invite à créer une issue différente. Le problème ne vient pas du CMS mais de votre serveur WEB. Ma version de DiamondCMS parvient par exemple bien à se connecter à votre serveur. 
![image](https://user-images.githubusercontent.com/64732248/120039622-8b567280-c005-11eb-8605-ec5a90a4185d.png)

**Comment by FireWax912** [comment]
Pour le forum j'ai encore eu le error 403 forbidden voici le rèlgmement qui est peut être un peu long 

Bonjour voici le règlement général du serveur AstraLifeRP

- Troll interdit sous peine de warn
- Insultes et propos homophobes, racistes ou mysogynes est interdit
- freekill / freeshoot / freepunch est interdit sous peine de warn
-  carkill interdit hors scène rp (pour troll par exemple)
- propblock interdit ( une structure bloquant un accès doit forcément être lié à un keypad accessible par tous les joueurs)
- propclimb/fly interdit sous peine de warn
- NLR interdit
- Metagaming interdit
- ForceRP interdit
- MassRP interdit
- Meurtrières interdites
- NoPainRP / No FearRP interdit 
- SpawnKill ( Mairie et commissariat) interdit
- HRP vocal interdit sauf si il permet d'aider quelqu'un qui, par exemple, a des difficultés dans un métier et que le staff est occupé
- Merci d'avoir également une conduite RP en ville et ses alentours

On espère que ce règlement sera respecté par tous afin d'avoir le meilleur confort de jeu possible !

FireWax | Fondateur

**Comment by Aldric-L** [comment]
En copie-collant votre message, je n'ai aucune erreur, c'est vraiment étrange, il est possible que ça vienne de vous.

**Comment by FireWax912** [comment]
Incroyable !

Je viens de le mettre avec mon téléphone portable et cela marche

**Comment by Aldric-L** [comment]
Parfait, ça ne vient donc pas du CMS. N’hésitez pas à me demander pour toute autre question.

**Comment by Aldric-L** [comment]
N’hésitez pas à fermer cette issue.
