### ISSUE TITLE
[BUG] Paypal

### ISSUE THREAD

**Issue by FireWax912** [Aldric-L/DiamondCMS#12]
Bonjour,

J'ai récemment créer un compte business sur paypal afin de pouvoir le configurer sur la boutique. 
Cependant, même en rentrant le token client dans l'id Paypal et le token secret Live, il y a une erreur quand on veut acheter

Merci de m'aider à régler ce bug

Cordialement

![image](https://user-images.githubusercontent.com/60072326/119792635-22bca800-bed6-11eb-93f7-343a4048f79d.png)

**Comment by Aldric-L** [comment]
(Re)Bonjour,
Paypal est un système extrêmement complexe à mettre en œuvre et le problème peut venir de nombreux niveaux. Je vous propose donc de procéder par ordre. 
Tout d'abord, vérifiez votre configuration de PayPal : par exemple avez-vous bien décoché la case "Sandbox" dans le CMS ? Par acquis de conscience, je vous invite à manuellement aller dans le fichier config/boutique.ini et à passer "sandbox" à 0 vu que vous avez un compte business. 

Inversement, avant de passer sur votre compte business, avez vous essayé avec vos identifiants de sandbox ? Les paiements Paypal ont été retesté dans le dernier Build du CMS et tout fonctionne correctement. L'erreur provient forcément d'un problème de configuration. Faites des essais, et n’hésitez pas à me transmettre vos résultats.

Effectuez cette première manipulation et tenez moi au courant. 
Merci de l'attention que vous portez au projet.
Bien cordialement.

**Comment by FireWax912** [comment]
rebonjour,

J'ai peut être oublié de vous préciser que dans les logs j'ai cette erreur : 

Type: Notice - 27/05/21 à 10:27:18 - Undefined property: stdClass::$expires_in. Affichée : Non - Levée dans /home/xyefzjky/public_html/models/paypal.class.php à la ligne 75. 
Type: Notice - 27/05/21 à 10:27:18 - Undefined property: stdClass::$access_token. Affichée : Non - Levée dans /home/xyefzjky/public_html/models/paypal.class.php à la ligne 72. 
Type: Notice - 27/05/21 à 10:26:14 - Undefined property: stdClass::$expires_in. Affichée : Non - Levée dans /home/xyefzjky/public_html/models/paypal.class.php à la ligne 75. 

Je ne sais pas si cela peut vous aider pour mon problème.

Cordialement,

**Comment by Aldric-L** [comment]
Normalement ces notices ne devraient pas nuire au bon fonctionnement de Paypal. Quelle version de PHP utilisez vous ?

**Comment by FireWax912** [comment]
Bonsoir Aldric-L, 

J'ai changer mes tokens avec ceux de la version Sandbox et ils marchent, la fenêtre de connexion et l'achat s'effectue correctement. Que dois-je faire selon vous pour que cela marche avec la version live ?

Cordialement

**Comment by Aldric-L** [comment]
Je vous ai répondu sur votre nouvelle issue. Il y a visiblement un problème dans le code, ce qui est étrange puisque d'autres parviennent à faire fonctionner Paypal business...

**Comment by Aldric-L** [comment]
Je vous invite à fermer cette issue si le problème est résolu.
Cordialement.
AL
