### ISSUE TITLE
Error with my connexion on my account

### ISSUE THREAD

**Issue by NeXoS-20** [Aldric-L/DiamondCMS#24]
Hello , i have a problem to connect my ADMIN account pls help me

**Comment by Aldric-L** [comment]
Tell me more please

**Comment by laboriens** [comment]
![image](https://user-images.githubusercontent.com/78578602/173832634-432f2c5c-9bec-4bdd-8519-fe0ee19b5c30.png)

**Comment by Aldric-L** [comment]
Bonjour @laboriens , 

Ce problème est bien une petite erreur dans le code. Vous pouvez ajouter ceci dans à la fin du fichier config.ini : 
`[boutique_ext]
link_boutique_externe = "ext/boutique/"
en_boutique_externe = "0"
`

Une V2 est en cours de développement. Nous présentons nos excuses pour la gêne occasionnée.
Je reste à votre disposition si besoin. 
Bien à vous.
AL

**Comment by laboriens** [comment]
![image](https://user-images.githubusercontent.com/78578602/173904611-e3888d35-eb38-4cc9-a72d-4b5d57ac1256.png)

**Comment by Aldric-L** [comment]
Êtes-vous sûr que votre couple identifiant/mot de passe est bien correct ?

**Comment by laboriens** [comment]
oui car j'ai un logiciel de mot de passe
